import type { Metadata } from 'next';
import Navbar from '@/app/navbar/Navbar';
import './globals.css';

export const metadata: Metadata = {
  title: 'Cseg - Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[var(--background)]">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
