import type { Metadata } from 'next';
import Navbar from '@/app/components/Navbar';
import './globals.css';
import { Playfair_Display } from 'next/font/google';

const playfairDisplay = Playfair_Display({
  subsets: ['latin', 'cyrillic'],
});

export const metadata: Metadata = {
  title: 'Cseg - Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className={playfairDisplay.className}>
      <body className="bg-[var(--background)]">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
